### ISSUE TITLE
Failed to control while using secondary screen

### ISSUE THREAD

**Issue by zisen123** [lujjjh/LitoMusic#40]
[![](https://pic.imgdb.cn/item/619adeda2ab3f51d9152927f.gif)](https://pic.imgdb.cn/item/619adeda2ab3f51d9152927f.gif)
windows 10 pro 20h2, laptop screen as secondary and external screen as main, unable to control (press the buttons or minimize the window) on secondary screen, but everything is ok when it's on main screen.

**Comment by lujjjh** [comment]
Thank you for reporting this issue.

I'm not able to reproduce it on Windows 10 21H1. Is it consistently reproducible on your side? What's the resolution and DPI scaling factor for each monitor?

**Comment by zisen123** [comment]
Sorry for reply late, I am using an external display 3840x2160@60 and DPI scaling is 150%, and my laptop internal display is 1920x1080@144 and DPI scaling is 125%.
I tried again and it occurs again when I move LitoMusic from external display to internal display.
When I am just using laptop internal display without using external display, it runs without problem.

**Comment by lujjjh** [comment]
Can confirm this issue. If a secondary monitor is positioned left / top to the primary one, the relative points could have negative x- and y- coordinates.

Could you test [this release](https://github.com/lujjjh/LitoMusic/actions/runs/1497960219) and see if this issue has been fixed?

**Comment by zisen123** [comment]
Thank you, this issue has been fixed in the updated version!
